import type { Product } from "./types";

const sizes = (spec: Record<number, number>) =>
  Object.entries(spec).map(([size, stockQty]) => ({
    size: Number(size),
    sku: `NS-${size}`,
    stockQty,
  }));

const RUN = { 39: 4, 40: 6, 41: 5, 42: 0, 43: 3, 44: 2, 45: 0 };
const RUN_B = { 38: 3, 39: 5, 40: 2, 41: 0, 42: 7, 43: 4, 44: 1 };
const RUN_W = { 36: 5, 37: 6, 38: 4, 39: 2, 40: 0, 41: 3 };
const RUN_K = { 28: 6, 29: 4, 30: 5, 31: 0, 32: 3, 33: 2 };
const RUN_LOW = { 39: 1, 40: 0, 41: 2, 42: 1 };

export const products: Product[] = [
  // MENS
  {
    id: "p-001",
    slug: "velocity-runner-white",
    name: "New Step Velocity Runner",
    brand: "New Step",
    category: "mens",
    categoryLabel: "Men's Running",
    subtitle: "Men's Running Shoe",
    colour: "White / Black",
    colourway: ["#ffffff", "#0a0a0a"],
    price: 12900,
    images: ["/images/p1.jpg", "/images/hero.jpg"],
    description: "A lightweight daily trainer built for Sri Lankan roads and long city days.",
    details: ["Engineered mesh upper for breathability", "Compression-moulded EVA midsole"],
    variants: sizes(RUN),
    isNew: true,
    isBestseller: true,
    rating: 4.8,
    reviewCount: 128,
  },
  {
    id: "p-002",
    slug: "shadow-chunky-black",
    name: "New Step Shadow Chunky",
    brand: "New Step",
    category: "mens",
    categoryLabel: "Men's Lifestyle",
    subtitle: "Men's Lifestyle Shoe",
    colour: "Triple Black",
    colourway: ["#0a0a0a"],
    price: 14500,
    images: ["/images/banner.jpg", "/images/p2.jpg"],
    description: "Statement volume, zero noise. Pairs a stacked sculpted sole with an all-black upper.",
    details: ["Layered leather and mesh upper", "Stacked 4cm sculpted midsole"],
    variants: sizes(RUN_B),
    rating: 4.5,
    reviewCount: 76,
  },
  {
    id: "p-003",
    slug: "heritage-oxford-tan",
    name: "New Step Heritage Oxford",
    brand: "New Step",
    category: "mens",
    categoryLabel: "Men's Formal",
    subtitle: "Men's Formal Shoe",
    colour: "Cognac Tan",
    colourway: ["#8a4a25"],
    price: 16900,
    images: ["/images/p3.jpg"],
    description: "Full-grain leather, cap-toe construction and a stacked heel. Office-ready in the morning.",
    details: ["Full-grain leather upper", "Cap-toe Oxford construction"],
    variants: sizes(RUN),
    isBestseller: true,
    rating: 4.9,
    reviewCount: 201,
  },
  {
    id: "p-010",
    slug: "trail-blazer-olive",
    name: "New Step Trail Blazer",
    brand: "New Step",
    category: "mens",
    categoryLabel: "Men's Outdoor",
    subtitle: "Men's Hiking Shoe",
    colour: "Olive / Black",
    colourway: ["#4a5d23", "#000000"],
    price: 15500,
    images: ["/images/hero.jpg", "/images/p1.jpg"],
    description: "Tough outsole for off-road trails and mountains.",
    details: ["Gore-tex coating", "Aggressive lug pattern"],
    variants: sizes(RUN_LOW),
    isNew: true,
    rating: 4.6,
    reviewCount: 32,
  },
  {
    id: "p-011",
    slug: "urban-slip-on",
    name: "New Step Urban Slip-On",
    brand: "New Step",
    category: "mens",
    categoryLabel: "Men's Casual",
    subtitle: "Men's Slip-On",
    colour: "Charcoal",
    colourway: ["#36454F"],
    price: 9900,
    images: ["/images/p2.jpg"],
    description: "Easy slip-on design for a relaxed weekend look.",
    details: ["Canvas upper", "Elastic side panels"],
    variants: sizes(RUN_B),
    rating: 4.2,
    reviewCount: 45,
  },
  {
    id: "p-012",
    slug: "elevate-trainer-navy",
    name: "New Step Elevate Trainer",
    brand: "New Step",
    category: "mens",
    categoryLabel: "Men's Training",
    subtitle: "Men's Gym Shoe",
    colour: "Navy Blue",
    colourway: ["#000080"],
    price: 11500,
    compareAtPrice: 13900,
    images: ["/images/p3.jpg"],
    description: "Flat sole for lifting, flexible toe box for agility.",
    details: ["TPU heel clip", "Breathable mesh"],
    variants: sizes(RUN),
    isBestseller: true,
    rating: 4.8,
    reviewCount: 150,
  },
  {
    id: "p-013",
    slug: "classic-leather-white",
    name: "New Step Classic Leather",
    brand: "New Step",
    category: "mens",
    categoryLabel: "Men's Lifestyle",
    subtitle: "Men's Sneaker",
    colour: "White",
    colourway: ["#ffffff"],
    price: 13900,
    images: ["/images/banner.jpg"],
    description: "Timeless white leather sneaker.",
    details: ["Premium leather upper", "Rubber cupsole"],
    variants: sizes(RUN),
    rating: 4.7,
    reviewCount: 305,
  },

  // WOMENS
  {
    id: "p-004",
    slug: "court-clean-womens",
    name: "New Step Court Clean",
    brand: "New Step",
    category: "womens",
    categoryLabel: "Women's Lifestyle",
    subtitle: "Women's Sneaker",
    colour: "White / Tan",
    colourway: ["#ffffff", "#c98c5c"],
    price: 11900,
    images: ["/images/p4.jpg"],
    description: "A clean court silhouette with a slightly raised sole for everyday comfort.",
    details: ["Soft leather upper", "Cushioned ortholite-style footbed"],
    variants: sizes(RUN_W),
    isNew: true,
    isBestseller: true,
    rating: 4.8,
    reviewCount: 93,
  },
  {
    id: "p-005",
    slug: "everyday-slide-black",
    name: "New Step Everyday Slide",
    brand: "New Step",
    category: "womens",
    categoryLabel: "Slides & Sandals",
    subtitle: "Unisex Slide",
    colour: "Black",
    colourway: ["#0a0a0a"],
    price: 3900,
    compareAtPrice: 5500,
    images: ["/images/p5.jpg"],
    description: "One-piece moulded EVA that shrugs off monsoon rain.",
    details: ["One-piece moulded EVA", "Water-friendly, quick drying"],
    variants: sizes(RUN_B),
    rating: 4.3,
    reviewCount: 211,
  },
  {
    id: "p-014",
    slug: "blossom-runner-pink",
    name: "New Step Blossom Runner",
    brand: "New Step",
    category: "womens",
    categoryLabel: "Women's Running",
    subtitle: "Women's Running Shoe",
    colour: "Dusty Pink",
    colourway: ["#DCAE96"],
    price: 12500,
    images: ["/images/p4.jpg"],
    description: "Soft cushioning for daily miles.",
    details: ["Flyknit upper", "Zoom foam"],
    variants: sizes(RUN_W),
    isNew: true,
    rating: 4.9,
    reviewCount: 88,
  },
  {
    id: "p-015",
    slug: "platform-canvas-white",
    name: "New Step Platform Canvas",
    brand: "New Step",
    category: "womens",
    categoryLabel: "Women's Casual",
    subtitle: "Women's Platform",
    colour: "White / Gum",
    colourway: ["#ffffff", "#d2b48c"],
    price: 8900,
    compareAtPrice: 10500,
    images: ["/images/p5.jpg"],
    description: "Elevate your style with a thick gum sole.",
    details: ["Organic canvas", "2-inch platform sole"],
    variants: sizes(RUN_W),
    isBestseller: true,
    rating: 4.7,
    reviewCount: 420,
  },
  {
    id: "p-016",
    slug: "luna-sandal-gold",
    name: "New Step Luna Sandal",
    brand: "New Step",
    category: "womens",
    categoryLabel: "Women's Sandals",
    subtitle: "Women's Sandal",
    colour: "Rose Gold",
    colourway: ["#B76E79"],
    price: 5500,
    images: ["/images/p4.jpg"],
    description: "Elegant strappy sandal for evening wear.",
    details: ["Metallic finish", "Adjustable ankle strap"],
    variants: sizes(RUN_LOW),
    rating: 4.4,
    reviewCount: 56,
  },
  {
    id: "p-017",
    slug: "core-flex-black",
    name: "New Step Core Flex",
    brand: "New Step",
    category: "womens",
    categoryLabel: "Women's Training",
    subtitle: "Women's Gym Shoe",
    colour: "Black / Rose",
    colourway: ["#000000", "#FF007F"],
    price: 11000,
    images: ["/images/p5.jpg"],
    description: "Flexible sole for studio workouts.",
    details: ["Sock-like fit", "Lightweight"],
    variants: sizes(RUN_W),
    rating: 4.8,
    reviewCount: 110,
  },
  {
    id: "p-018",
    slug: "court-clean-noir-w",
    name: "New Step Court Clean Noir",
    brand: "New Step",
    category: "womens",
    categoryLabel: "Women's Lifestyle",
    subtitle: "Women's Sneaker",
    colour: "Black",
    colourway: ["#0a0a0a"],
    price: 11900,
    images: ["/images/p4.jpg"],
    description: "The Court Clean in an all-black finish.",
    details: ["Soft leather upper", "Cushioned footbed"],
    variants: sizes(RUN_W),
    rating: 4.6,
    reviewCount: 37,
  },

  // KIDS
  {
    id: "p-006",
    slug: "junior-step-blue",
    name: "New Step Junior Step",
    brand: "New Step",
    category: "kids",
    categoryLabel: "Kids' Shoes",
    subtitle: "Kids' Sneaker",
    colour: "White / Blue",
    colourway: ["#ffffff", "#1a63c4"],
    price: 6900,
    images: ["/images/p6.jpg"],
    description: "Easy hook-and-loop strap so little ones can do it themselves.",
    details: ["Hook-and-loop strap", "Flexible non-marking outsole"],
    variants: sizes(RUN_K),
    isBestseller: true,
    rating: 4.9,
    reviewCount: 241,
  },
  {
    id: "p-019",
    slug: "playground-hero-red",
    name: "New Step Playground Hero",
    brand: "New Step",
    category: "kids",
    categoryLabel: "Kids' Active",
    subtitle: "Kids' Sneaker",
    colour: "Red / Black",
    colourway: ["#ff0000", "#000000"],
    price: 7500,
    images: ["/images/p6.jpg"],
    description: "Built tough for endless playground energy.",
    details: ["Reinforced toe cap", "Breathable mesh"],
    variants: sizes(RUN_K),
    isNew: true,
    rating: 4.7,
    reviewCount: 89,
  },
  {
    id: "p-020",
    slug: "tiny-tots-pink",
    name: "New Step Tiny Tots",
    brand: "New Step",
    category: "kids",
    categoryLabel: "Toddler Shoes",
    subtitle: "Toddler Sneaker",
    colour: "Soft Pink",
    colourway: ["#FFC0CB"],
    price: 5500,
    images: ["/images/p6.jpg"],
    description: "Soft sole shoes for first steps.",
    details: ["Ultra soft leather", "Wide toe box"],
    variants: sizes(RUN_K),
    rating: 4.9,
    reviewCount: 320,
  },
  {
    id: "p-021",
    slug: "school-smart-black",
    name: "New Step School Smart",
    brand: "New Step",
    category: "kids",
    categoryLabel: "School Shoes",
    subtitle: "Kids' Formal",
    colour: "Black",
    colourway: ["#000000"],
    price: 6500,
    compareAtPrice: 7500,
    images: ["/images/p6.jpg"],
    description: "Durable school shoes that meet uniform standards.",
    details: ["Polishable leather", "Scuff resistant"],
    variants: sizes(RUN_K),
    isBestseller: true,
    rating: 4.8,
    reviewCount: 450,
  },
  {
    id: "p-022",
    slug: "splash-boots-yellow",
    name: "New Step Splash Boots",
    brand: "New Step",
    category: "kids",
    categoryLabel: "Rain Boots",
    subtitle: "Kids' Boots",
    colour: "Bright Yellow",
    colourway: ["#FFFF00"],
    price: 4900,
    images: ["/images/p6.jpg"],
    description: "100% waterproof for jumping in puddles.",
    details: ["Rubber construction", "Cotton lining"],
    variants: sizes(RUN_K),
    rating: 4.6,
    reviewCount: 65,
  }
];

export const categories = [
  { slug: "mens", name: "Men's", image: "/images/p1.jpg", blurb: "Runners, lifestyle and formal" },
  { slug: "womens", name: "Women's", image: "/images/p4.jpg", blurb: "Court, casual and slides" },
  { slug: "kids", name: "Kids'", image: "/images/p6.jpg", blurb: "School-ready and play-proof" },
] as const;

export const getProduct = (slug: string) => products.find((p) => p.slug === slug);

export const byCategory = (slug: string) =>
  slug === "all" ? products : products.filter((p) => p.category === slug);

export const totalStock = (p: Product) =>
  p.variants.reduce((sum, v) => sum + v.stockQty, 0);

export const relatedTo = (p: Product) =>
  products.filter((x) => x.id !== p.id && x.category === p.category).slice(0, 4);
