import type { Product } from "./types";

const sizes = (spec: Record<number, number>) =>
  Object.entries(spec).map(([size, stockQty]) => ({
    size: Number(size),
    sku: `NS-${size}`,
    stockQty,
  }));

const RUN = { 39: 4, 40: 6, 41: 5, 42: 0, 43: 3, 44: 2, 45: 0 };
const RUN_B = { 38: 3, 39: 5, 40: 2, 41: 0, 42: 7, 43: 4, 44: 1 };
const RUN_W = { 36: 5, 37: 6, 38: 4, 39: 2, 40: 0, 41: 3 };
const RUN_K = { 28: 6, 29: 4, 30: 5, 31: 0, 32: 3, 33: 2 };
const RUN_LOW = { 39: 1, 40: 0, 41: 2, 42: 1 };

export const products: Product[] = [
  // MENS
  {
    id: "p-001",
    slug: "velocity-runner-white",
    name: "New Step Velocity Runner",
    brand: "New Step",
    category: "mens",
    categoryLabel: "Men's Running",
    subtitle: "Men's Running Shoe",
    colour: "White / Black",
    colourway: ["#ffffff", "#0a0a0a"],
    price: 12900,
    images: ["/images/p1.jpg", "/images/hero.jpg"],
    description: "A lightweight daily trainer built for Sri Lankan roads and long city days.",
    details: ["Engineered mesh upper for breathability", "Compression-moulded EVA midsole"],
    variants: sizes(RUN),
    isNew: true,
    isBestseller: true,
  },
  {
    id: "p-002",
    slug: "shadow-chunky-black",
    name: "New Step Shadow Chunky",
    brand: "New Step",
    category: "mens",
    categoryLabel: "Men's Lifestyle",
    subtitle: "Men's Lifestyle Shoe",
    colour: "Triple Black",
    colourway: ["#0a0a0a"],
    price: 14500,
    images: ["/images/banner.jpg", "/images/p2.jpg"],
    description: "Statement volume, zero noise. Pairs a stacked sculpted sole with an all-black upper.",
    details: ["Layered leather and mesh upper", "Stacked 4cm sculpted midsole"],
    variants: sizes(RUN_B),
  },
  {
    id: "p-003",
    slug: "heritage-oxford-tan",
    name: "New Step Heritage Oxford",
    brand: "New Step",
    category: "mens",
    categoryLabel: "Men's Formal",
    subtitle: "Men's Formal Shoe",
    colour: "Cognac Tan",
    colourway: ["#8a4a25"],
    price: 16900,
    images: ["/images/p3.jpg"],
    description: "Full-grain leather, cap-toe construction and a stacked heel. Office-ready in the morning.",
    details: ["Full-grain leather upper", "Cap-toe Oxford construction"],
    variants: sizes(RUN),
    isBestseller: true,
  },
  {
    id: "p-010",
    slug: "trail-blazer-olive",
    name: "New Step Trail Blazer",
    brand: "New Step",
    category: "mens",
    categoryLabel: "Men's Outdoor",
    subtitle: "Men's Hiking Shoe",
    colour: "Olive / Black",
    colourway: ["#4a5d23", "#000000"],
    price: 15500,
    images: ["/images/hero.jpg", "/images/p1.jpg"],
    description: "Tough outsole for off-road trails and mountains.",
    details: ["Gore-tex coating", "Aggressive lug pattern"],
    variants: sizes(RUN_LOW),
    isNew: true,
  },
  {
    id: "p-011",
    slug: "urban-slip-on",
    name: "New Step Urban Slip-On",
    brand: "New Step",
    category: "mens",
    categoryLabel: "Men's Casual",
    subtitle: "Men's Slip-On",
    colour: "Charcoal",
    colourway: ["#36454F"],
    price: 9900,
    images: ["/images/p2.jpg"],
    description: "Easy slip-on design for a relaxed weekend look.",
    details: ["Canvas upper", "Elastic side panels"],
    variants: sizes(RUN_B),
  },
  {
    id: "p-012",
    slug: "elevate-trainer-navy",
    name: "New Step Elevate Trainer",
    brand: "New Step",
    category: "mens",
    categoryLabel: "Men's Training",
    subtitle: "Men's Gym Shoe",
    colour: "Navy Blue",
    colourway: ["#000080"],
    price: 11500,
    compareAtPrice: 13900,
    images: ["/images/p3.jpg"],
    description: "Flat sole for lifting, flexible toe box for agility.",
    details: ["TPU heel clip", "Breathable mesh"],
    variants: sizes(RUN),
    isBestseller: true,
  },
  {
    id: "p-013",
    slug: "classic-leather-white",
    name: "New Step Classic Leather",
    brand: "New Step",
    category: "mens",
    categoryLabel: "Men's Lifestyle",
    subtitle: "Men's Sneaker",
    colour: "White",
    colourway: ["#ffffff"],
    price: 13900,
    images: ["/images/banner.jpg"],
    description: "Timeless white leather sneaker.",
    details: ["Premium leather upper", "Rubber cupsole"],
    variants: sizes(RUN),
  },

  // WOMENS
  {
    id: "p-004",
    slug: "court-clean-womens",
    name: "New Step Court Clean",
    brand: "New Step",
    category: "womens",
    categoryLabel: "Women's Lifestyle",
    subtitle: "Women's Sneaker",
    colour: "White / Tan",
    colourway: ["#ffffff", "#c98c5c"],
    price: 11900,
    images: ["/images/p4.jpg"],
    description: "A clean court silhouette with a slightly raised sole for everyday comfort.",
    details: ["Soft leather upper", "Cushioned ortholite-style footbed"],
    variants: sizes(RUN_W),
    isNew: true,
    isBestseller: true,
  },
  {
    id: "p-005",
    slug: "everyday-slide-black",
    name: "New Step Everyday Slide",
    brand: "New Step",
    category: "womens",
    categoryLabel: "Slides & Sandals",
    subtitle: "Unisex Slide",
    colour: "Black",
    colourway: ["#0a0a0a"],
    price: 3900,
    compareAtPrice: 5500,
    images: ["/images/p5.jpg"],
    description: "One-piece moulded EVA that shrugs off monsoon rain.",
    details: ["One-piece moulded EVA", "Water-friendly, quick drying"],
    variants: sizes(RUN_B),
  },
  {
    id: "p-014",
    slug: "blossom-runner-pink",
    name: "New Step Blossom Runner",
    brand: "New Step",
    category: "womens",
    categoryLabel: "Women's Running",
    subtitle: "Women's Running Shoe",
    colour: "Dusty Pink",
    colourway: ["#DCAE96"],
    price: 12500,
    images: ["/images/p4.jpg"],
    description: "Soft cushioning for daily miles.",
    details: ["Flyknit upper", "Zoom foam"],
    variants: sizes(RUN_W),
    isNew: true,
  },
  {
    id: "p-015",
    slug: "platform-canvas-white",
    name: "New Step Platform Canvas",
    brand: "New Step",
    category: "womens",
    categoryLabel: "Women's Casual",
    subtitle: "Women's Platform",
    colour: "White / Gum",
    colourway: ["#ffffff", "#d2b48c"],
    price: 8900,
    compareAtPrice: 10500,
    images: ["/images/p5.jpg"],
    description: "Elevate your style with a thick gum sole.",
    details: ["Organic canvas", "2-inch platform sole"],
    variants: sizes(RUN_W),
    isBestseller: true,
  },
  {
    id: "p-016",
    slug: "luna-sandal-gold",
    name: "New Step Luna Sandal",
    brand: "New Step",
    category: "womens",
    categoryLabel: "Women's Sandals",
    subtitle: "Women's Sandal",
    colour: "Rose Gold",
    colourway: ["#B76E79"],
    price: 5500,
    images: ["/images/p4.jpg"],
    description: "Elegant strappy sandal for evening wear.",
    details: ["Metallic finish", "Adjustable ankle strap"],
    variants: sizes(RUN_LOW),
  },
  {
    id: "p-017",
    slug: "core-flex-black",
    name: "New Step Core Flex",
    brand: "New Step",
    category: "womens",
    categoryLabel: "Women's Training",
    subtitle: "Women's Gym Shoe",
    colour: "Black / Rose",
    colourway: ["#000000", "#FF007F"],
    price: 11000,
    images: ["/images/p5.jpg"],
    description: "Flexible sole for studio workouts.",
    details: ["Sock-like fit", "Lightweight"],
    variants: sizes(RUN_W),
  },
  {
    id: "p-018",
    slug: "court-clean-noir-w",
    name: "New Step Court Clean Noir",
    brand: "New Step",
    category: "womens",
    categoryLabel: "Women's Lifestyle",
    subtitle: "Women's Sneaker",
    colour: "Black",
    colourway: ["#0a0a0a"],
    price: 11900,
    images: ["/images/p4.jpg"],
    description: "The Court Clean in an all-black finish.",
    details: ["Soft leather upper", "Cushioned footbed"],
    variants: sizes(RUN_W),
  },

  // KIDS
  {
    id: "p-006",
    slug: "junior-step-blue",
    name: "New Step Junior Step",
    brand: "New Step",
    category: "kids",
    categoryLabel: "Kids' Shoes",
    subtitle: "Kids' Sneaker",
    colour: "White / Blue",
    colourway: ["#ffffff", "#1a63c4"],
    price: 6900,
    images: ["/images/p6.jpg"],
    description: "Easy hook-and-loop strap so little ones can do it themselves.",
    details: ["Hook-and-loop strap", "Flexible non-marking outsole"],
    variants: sizes(RUN_K),
    isBestseller: true,
  },
  {
    id: "p-019",
    slug: "playground-hero-red",
    name: "New Step Playground Hero",
    brand: "New Step",
    category: "kids",
    categoryLabel: "Kids' Active",
    subtitle: "Kids' Sneaker",
    colour: "Red / Black",
    colourway: ["#ff0000", "#000000"],
    price: 7500,
    images: ["/images/p6.jpg"],
    description: "Built tough for endless playground energy.",
    details: ["Reinforced toe cap", "Breathable mesh"],
    variants: sizes(RUN_K),
    isNew: true,
  },
  {
    id: "p-020",
    slug: "tiny-tots-pink",
    name: "New Step Tiny Tots",
    brand: "New Step",
    category: "kids",
    categoryLabel: "Toddler Shoes",
    subtitle: "Toddler Sneaker",
    colour: "Soft Pink",
    colourway: ["#FFC0CB"],
    price: 5500,
    images: ["/images/p6.jpg"],
    description: "Soft sole shoes for first steps.",
    details: ["Ultra soft leather", "Wide toe box"],
    variants: sizes(RUN_K),
  },
  {
    id: "p-021",
    slug: "school-smart-black",
    name: "New Step School Smart",
    brand: "New Step",
    category: "kids",
    categoryLabel: "School Shoes",
    subtitle: "Kids' Formal",
    colour: "Black",
    colourway: ["#000000"],
    price: 6500,
    compareAtPrice: 7500,
    images: ["/images/p6.jpg"],
    description: "Durable school shoes that meet uniform standards.",
    details: ["Polishable leather", "Scuff resistant"],
    variants: sizes(RUN_K),
    isBestseller: true,
  },
  {
    id: "p-022",
    slug: "splash-boots-yellow",
    name: "New Step Splash Boots",
    brand: "New Step",
    category: "kids",
    categoryLabel: "Rain Boots",
    subtitle: "Kids' Boots",
    colour: "Bright Yellow",
    colourway: ["#FFFF00"],
    price: 4900,
    images: ["/images/p6.jpg"],
    description: "100% waterproof for jumping in puddles.",
    details: ["Rubber construction", "Cotton lining"],
    variants: sizes(RUN_K),
    rating: 4.6,
    reviewCount: 14,
  },

  // NEW CATALOG EXPANSIONS
  {
    id: "p-023",
    slug: "apex-street-sneaker-slate",
    name: "New Step Apex Street",
    brand: "New Step",
    category: "mens",
    categoryLabel: "Men's Lifestyle",
    subtitle: "Men's Street Runner",
    colour: "White / Slate Blue",
    colourway: ["#FFFFFF", "#4A6B82"],
    price: 13900,
    compareAtPrice: 16500,
    images: ["/images/p7.jpg", "/images/hero.jpg"],
    description: "Modern urban runner with layered ripstop panels, cushioned midsole, and a clean architectural silhouette.",
    details: ["Breathable technical mesh and suede overlays", "High-density EVA foam midsole", "Non-slip rubber tread outsole"],
    variants: sizes(RUN),
    isNew: true,
    isBestseller: true,
    rating: 4.8,
    reviewCount: 34,
  },
  {
    id: "p-024",
    slug: "summit-trekker-boot-tobacco",
    name: "New Step Summit Trekker",
    brand: "New Step",
    category: "mens",
    categoryLabel: "Men's Outdoor",
    subtitle: "Men's Hiking Boot",
    colour: "Tobacco Brown",
    colourway: ["#6E472A", "#2B1A10"],
    price: 18500,
    compareAtPrice: 22000,
    images: ["/images/p8.jpg", "/images/p3.jpg"],
    description: "Rugged full-grain leather hiking boot engineered for unpredictable tropical trails and mountain treks.",
    details: ["Waterproof treated full-grain leather", "Deep-lug Vibram traction sole", "Padded ankle collar for support"],
    variants: sizes(RUN_B),
    isNew: true,
    rating: 4.9,
    reviewCount: 42,
  },
  {
    id: "p-025",
    slug: "monaco-penny-loafer-espresso",
    name: "New Step Monaco Loafer",
    brand: "New Step",
    category: "mens",
    categoryLabel: "Men's Formal",
    subtitle: "Men's Penny Loafer",
    colour: "Espresso Suede",
    colourway: ["#3D2B1F"],
    price: 15900,
    images: ["/images/p9.jpg", "/images/p3.jpg"],
    description: "Tailored penny loafer crafted in velvety calf suede. Effortlessly bridges boardrooms and weekend galas.",
    details: ["Hand-stitched apron welt", "Supple calf suede leather", "Cushioned memory-foam insole"],
    variants: sizes(RUN),
    isBestseller: true,
    rating: 4.7,
    reviewCount: 28,
  },
  {
    id: "p-026",
    slug: "aura-velocity-runner-peach",
    name: "New Step Aura Velocity",
    brand: "New Step",
    category: "womens",
    categoryLabel: "Women's Running",
    subtitle: "Women's Performance Runner",
    colour: "Lavender / Peach",
    colourway: ["#C8B6E2", "#FFCBA4"],
    price: 14200,
    compareAtPrice: 17000,
    images: ["/images/p10.jpg", "/images/p4.jpg"],
    description: "Chic high-energy road runner designed for female ergonomics, maximum rebound, and featherlight endurance.",
    details: ["Engineered stretch-knit bootie upper", "Dual-density responsive foam core", "Reflective safety accents for dusk runs"],
    variants: sizes(RUN_W),
    isNew: true,
    isBestseller: true,
    rating: 4.9,
    reviewCount: 56,
  },
  {
    id: "p-027",
    slug: "stella-block-heel-cream",
    name: "New Step Stella Block Heel",
    brand: "New Step",
    category: "womens",
    categoryLabel: "Women's Casual",
    subtitle: "Women's Mule Heel",
    colour: "Warm Cream",
    colourway: ["#FFFDD0", "#C9A84C"],
    price: 11500,
    images: ["/images/p11.jpg", "/images/p5.jpg"],
    description: "Contemporary square-toe mule with a balanced sculptural block heel for all-day cocktail poise.",
    details: ["Vegan butter-soft nappa leather", "6cm stable architectural block heel", "Anti-slip rubberized heel tap"],
    variants: sizes(RUN_W),
    isNew: true,
    rating: 4.8,
    reviewCount: 19,
  },
  {
    id: "p-028",
    slug: "horizon-trail-sneaker-sage",
    name: "New Step Horizon Trail",
    brand: "New Step",
    category: "womens",
    categoryLabel: "Women's Outdoor",
    subtitle: "Women's Trail Runner",
    colour: "Sage Green / Taupe",
    colourway: ["#9CA986", "#B8A398"],
    price: 13800,
    compareAtPrice: 15900,
    images: ["/images/p12.jpg", "/images/p4.jpg"],
    description: "All-weather outdoor runner equipped with ripstop protection, mudguard overlay, and ultra-grippy traction.",
    details: ["Hydrophobic water-shedding mesh", "Reinforced rubber toe cap guard", "Multidirectional trail traction lugs"],
    variants: sizes(RUN_W),
    isBestseller: true,
    rating: 4.7,
    reviewCount: 31,
  },
  {
    id: "p-029",
    slug: "kids-spark-sneaker-lime",
    name: "New Step Spark Light-Up",
    brand: "New Step",
    category: "kids",
    categoryLabel: "Kids' Active",
    subtitle: "Kids' LED Sneaker",
    colour: "Navy / Neon Lime",
    colourway: ["#0B2F64", "#7FFF00"],
    price: 7900,
    compareAtPrice: 9200,
    images: ["/images/p13.jpg", "/images/p6.jpg"],
    description: "Dynamic athletic trainer with responsive motion-activated LED lights in the sole for active kids.",
    details: ["Impact-activated bright LED sole lights", "Easy quick-strap hook & loop fastener", "Non-marking flexible gum sole"],
    variants: sizes(RUN_K),
    isNew: true,
    isBestseller: true,
    rating: 4.9,
    reviewCount: 47,
  },
  {
    id: "p-030",
    slug: "kids-adventure-sandal-teal",
    name: "New Step Adventure Sandal",
    brand: "New Step",
    category: "kids",
    categoryLabel: "Kids' Shoes",
    subtitle: "Kids' Sport Sandal",
    colour: "Teal / Charcoal",
    colourway: ["#008080", "#36454F"],
    price: 5400,
    images: ["/images/p14.jpg", "/images/p6.jpg"],
    description: "Water-ready adventure sandal with triple adjustable velcro straps for beach trips, rain, and park exploration.",
    details: ["Quick-drying water-friendly webbing", "Contoured antimicrobial EVA footbed", "Rugged shock-absorbing traction base"],
    variants: sizes(RUN_K),
    isNew: true,
    rating: 4.8,
    reviewCount: 22,
  },
];

export const categories = [
  { slug: "mens", name: "Men's", image: "/images/p1.jpg", blurb: "Runners, lifestyle and formal" },
  { slug: "womens", name: "Women's", image: "/images/p4.jpg", blurb: "Court, casual and slides" },
  { slug: "kids", name: "Kids'", image: "/images/p6.jpg", blurb: "School-ready and play-proof" },
] as const;

export const getProduct = (slug: string) => products.find((p) => p.slug === slug);

export const byCategory = (slug: string) =>
  slug === "all" ? products : products.filter((p) => p.category === slug);

export const totalStock = (p: Product) =>
  p.variants.reduce((sum, v) => sum + v.stockQty, 0);

export const relatedTo = (p: Product) =>
  products.filter((x) => x.id !== p.id && x.category === p.category).slice(0, 4);

export const bestSellers = products.filter((p) => p.isBestseller || (p.rating && p.rating >= 4.7));
export const newArrivals = products.filter((p) => p.isNew);
export const onSaleProducts = products.filter((p) => !!p.compareAtPrice);

